version: 1.2
workflows:
 - name: RefNAAP-wdl
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_refnaap.wdl
   testParameterFiles:
    - /test/inputs/empty.json

workflows:
  - name: RaBVGlue-wdl
    subclass: WDL
    primaryDescriptorPath: /workflows/wf_rabvglue.wdl
    testParameterFiles:
      - /test/inputs/empty.json
